version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing kubectl...
      - curl -LO "https://k8s.io"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Installing Trivy...
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      - echo Running Unit Tests...
      - pip install -r requirements.txt
      - python -m pytest 
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 044014415460.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t python-devsecops .
      - docker tag python-devsecops:latest 044014415460.dkr.ecr.ap-south-1.amazonaws.com/python-devsecops:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 044014415460.dkr.ecr.ap-south-1.amazonaws.com/python-devsecops:latest
      - echo Running Trivy security scan...
      - trivy image --severity HIGH,CRITICAL 044014415460.dkr.ecr.ap-south-1.amazonaws.com/python-devsecops:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region ap-south-1 --name devsecops-cluster
      - echo Deploying to Kubernetes...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - '**/*' # This fixes the 'NoSuchKey' error by passing files to the next stage
